#
# Makefile generated by:
# codebench 0.55
#
# Project: PWGen
#
# Created on: 02-01-2024 16:46:39
#
#

###################################################################
##
##////  Objects
##
###################################################################

PWGen_OBJ := \
	 /RAM/PWGEn.o


###################################################################
##
##////  Variables and Environment
##
###################################################################

CC := gcc:bin/gcc

INCPATH := -I.

CFLAGS := $(INCPATH) -Wall -Werror -Wwrite-strings


###################################################################
##
##////  General rules
##
###################################################################

.PHONY: all all-before all-after clean clean-custom realclean

all: all-before PWGen all-after

all-before:
#	You can add rules here to execute before the project is built

all-after:
#	You can add rules here to execute after the project is built

clean: clean-custom
	@echo "Cleaning compiler objects..."
	@rm -f  $(PWGen_OBJ)

realclean:
	@echo "Cleaning compiler objects and targets..."
	@rm -f  $(PWGen_OBJ) PWGen


###################################################################
##
##////  Targets
##
###################################################################

PWGen: $(PWGen_OBJ)
	@echo "Linking PWGen"
	@gcc:bin/gcc -o PWGen $(PWGen_OBJ) -lauto
	@echo "Removing stale debug target: PWGen"
	@rm -f PWGen.debug


###################################################################
##
##////  Standard rules
##
###################################################################

# A default rule to make all the objects listed below
# because we are hiding compiler commands from the output

.c.o:
	@echo "Compiling $<"
	@$(CC) -c $< -o $*.o $(CFLAGS)

/RAM/PWGEn.o: /RAM/PWGEn.c

